apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: messaging
  labels:
    strimzi.io/cluster: three-tier-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral