apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sathishpadmanaban01-cmd/three-tier-app.git
    targetRevision: HEAD
    path: gitops/apps/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
