apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            - name: MONGO_DB
              value: {{ .Values.env.MONGO_DB | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
            - name: KAFKA_TOPIC_ORDERS
              value: {{ .Values.env.KAFKA_TOPIC_ORDERS | quote }}
